In [ ]:
1. Import numpy as np and see the version (Score 1)
2. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5
matrix. (Score:1)
3. Create a numpy array containing the numbers from 1 to 20, and then extract the
elements between the 5th and 15th index. (Score :2)
4. How to compute the mean, median, standard deviation of a numpy array?Use the array
you created above (Score 3)
5. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of
shape (4,). Subtract y from each row of x using broadcasting. (Score : 2) Note : Score 1
for timely submission.

In [2]:
import numpy as np
print(np.__version__)

2.3.4


In [3]:
arr = np.arange(1, 11)
print(arr)
reshaped_arr = arr.reshape(2, 5)
print(reshaped_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
arr2 = np.arange(1, 21)
extracted = arr2[5:16]  
print(extracted)

[ 6  7  8  9 10 11 12 13 14 15 16]


In [5]:
mean_val = np.mean(arr2)
median_val = np.median(arr2)
std_val = np.std(arr2)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)


Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


In [6]:
x = np.arange(12).reshape(3, 4)
y = np.array([1, 2, 3, 4])

result = x - y
print(result)


[[-1 -1 -1 -1]
 [ 3  3  3  3]
 [ 7  7  7  7]]
