In [ ]:
1. Import numpy as np and see the version (Score 1)
2. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5
matrix. (Score:1)
3. Create a numpy array containing the numbers from 1 to 20, and then extract the
elements between the 5th and 15th index. (Score :2)
4. How to compute the mean, median, standard deviation of a numpy array?Use the array
you created above (Score 3)
5. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of
shape (4,). Subtract y from each row of x using broadcasting. (Score : 2) Note : Score 1
for timely submission.

In [1]:
import numpy as np

In [8]:
arr = np.arange(1,11)

In [10]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr_reshape = arr.reshape(2,5)

In [15]:
arr_reshape


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
arr_2 = np.arange(1,21)

In [17]:
arr_2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
arr_2[5:16]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [31]:
mean = np.mean(arr_2)

In [33]:
print(mean)

10.5


In [34]:
median=np.median(arr_2)

In [35]:
print(median)

10.5


In [36]:
std = np.std(arr_2)
print(std)

5.766281297335398


In [37]:
empty = np.empty((2, 2)) 

In [38]:
empty

array([[1.13654010e-299, 1.33360534e+241],
       [3.98430174e-309, 2.24261889e-205]])

In [39]:
full = np.full((2, 3), 7)

In [40]:
full

array([[7, 7, 7],
       [7, 7, 7]])

In [48]:
np.full((10,10),100)

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [53]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [54]:
random_uniform = np.random.rand(3, 3)        # Uniform [0, 1)


In [57]:
random_uniform

array([[0.67298719, 0.881695  , 0.78579812],
       [0.55901691, 0.35915285, 0.4016203 ],
       [0.57676106, 0.1840137 , 0.33376826]])

In [55]:
random_normal = np.random.randn(3, 3)        # Standard normal distribution


In [58]:
random_normal

array([[ 1.14969464e+00, -8.45628783e-01, -1.97128586e+00],
       [ 6.63808370e-01, -2.33542538e-01, -5.17948629e-01],
       [ 1.32567379e-01,  1.05745023e-03, -1.40048359e+00]])

In [56]:
random_int = np.random.randint(0, 10, (3, 3)) # R

In [59]:
random_int

array([[4, 1, 2],
       [2, 7, 4],
       [5, 0, 0]], dtype=int32)