In [ ]:
In this assignment, you will apply Linear Algebra and Probability techniques to analyze the Wine
Quality Dataset. The dataset consists of 1599 rows and 12 columns, detailing various chemical
properties of red and white wines and their quality scores. Your tasks will focus on vectors,
matrices, eigenvalues, eigenvectors, and basic probability concepts. You can download the
dataset from the link given below. The dataset contains 1599 samples of wine, with features
such as acidity, alcohol content, pH, residual sugar, and others, alongside the target variable,
wine quality.
1. Load the dataset and handle any missing data by replacing null values with the mean
value of the respective column. (Score 2)
2. Extract the following columns as vectors: alcohol,citric acid. (Score 2)
3. Select two features (e.g., alcohol and density) from the dataset and calculate the
covariance matrix using np.cov(X.T), where X is the feature matrix consisting of the
selected columns.(Score 2)
4. Perform eigen decomposition on the covariance matrix you computed in question 3.
Identify and interpret the results:Identify the top 2 eigenvalues of the covariance
matrix,Identify the corresponding eigenvectors.(Score 2)
5. Which wine quality is most common in the dataset? How can you interpret the
distribution of wine quality scores? (Score 2)
https://drive.google.com/file/d/1OnJ8qjX8HAlNU5JCHFRdYjMHLd78Ft56/view?usp=drive_link

In [28]:
import pandas as pd
import numpy as np

df = pd.read_csv("winquality.csv")

In [26]:
import pandas as pd
import numpy as np

df = pd.read_csv("winquality.csv")

# 1. Load the dataset and handle any missing data by replacing null values with the mean value of the respective column. (Score 2)

In [29]:
df = df.fillna(df.mean(numeric_only=True))

In [30]:
df


,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5


In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [32]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

# 2. Extract the following columns as vectors: alcohol,citric acid. (Score 2)

In [35]:
alchohol = df['alcohol'].values
citric_acid = df['citric acid'].values

In [36]:
alchohol

array([ 9.4,  9.8,  9.8, ..., 11. , 10.2, 11. ], shape=(1599,))

In [37]:
citric_acid

array([0.  , 0.  , 0.04, ..., 0.13, 0.12, 0.47], shape=(1599,))

# 3. Select two features (e.g., alcohol and density) from the dataset and calculate the covariance matrix using np.cov(X.T), where X is the feature matrix consisting of the selected columns.(Score 2)

In [44]:
X = df[['alcohol','density']].values

In [45]:
covariance = np.cov(X.T)

In [46]:
covariance

array([[ 1.13564740e+00, -9.97951790e-04],
       [-9.97951790e-04,  3.56202945e-06]])

# 4. Perform eigen decomposition on the covariance matrix you computed in question 3. Identify and interpret the results:Identify the top 2 eigenvalues of the covariance matrix,Identify the corresponding eigenvectors.(Score 2)

In [47]:
eigen_val, eigen_vector = np.linalg.eig(covariance)

In [53]:
for e in eigen_val:
    print(e)

1.1356482719541243
2.6850758026699082e-06


In [49]:
eigen_vector

array([[ 9.99999614e-01,  8.78753184e-04],
       [-8.78753184e-04,  9.99999614e-01]])

# 5. Which wine quality is most common in the dataset? How can you interpret the distribution of wine quality scores? (Score 2)

In [54]:
df['quality'].value_counts

<bound method IndexOpsMixin.value_counts of 0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64>